const Numero1=parseFloat(prompt("ingresa un numero"));
const Numero2=parseFloat(prompt("ingresa un numero: "));
const suma=Numero1+Numero2;
const resta=Numero1-Numero2;
const multiplicacion=Numero1*Numero2;
const division=Numero1/Numero2;
console.log( {suma});
console.log({resta});
console.log({multiplicacion});
console.log({division});
